### PR TITLE
TNW page clone 

### PR DESCRIPTION
**Pull request by SevlaMare**
-Initial Setup and Linter Check.
-Added images and icons on root folder.
-Added Html basic structure.
-Basic style position and align.
-Added grids with media queries.
-Improved Navbar for mobile.
-Fix all issues with Linter and validator.
-Move all media queries to the end.
-Fixed margins for breakpoints: smartphone, tablet and laptop 11'' screen.
-style code refactoring, now is mobile first approach

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback :handshake:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @SevlaMare and @paulgureghian! :clap: 
You've done great building this and you're well on your way to a fine completion! Please consider my comments below, make the necessary changes and request your next review! I wish you all the best :100: 

#### Responsiveness
Your project could use a little more responsiveness, please look a little more closely at the sizes of elements, padding of sections, margins, and general element positionings. These are very key as they will affect the look, feel, and more importantly the usability of your sites. I went ahead to attach a few images of areas where I noticed issues with responsiveness, however, please do a full scan of your page just in case I missed or left something out.
screenshot
screenshot
screenshot

Also, note that the image overlays(Darkened box ontop each image) are missing in the first section. Please consider implementing it.

Please look into responsiveness thoroughly as it is a major project requirement! Use your browser's dev tools to test all screen sizes and compare adequately with the original site.

#### Missing logo
The TNW logo doesn't seem to show up in the navigation bar on all screen sizes, please look into this and make the appropriate change, afterward, request another review! I wish you the very best and see you at the top! :rocket: 

### Summary
Please consider your project in all screen sizes and compare what happens at each breakpoint with what happens on the original site, I wish you all the best in your endeavours :smile: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by SevlaMare** [comment]
> I went ahead to attach a few images of areas where I noticed issues with responsiveness, however, please do a full scan of your page just in case I missed or left something out.

The responsiveness was broken because we forget to add a meta element (tag) on head, now is working fine.
The logo and background will be added.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @SevlaMare, you did a great job implementing the changes requested by the previous reviewer. 👍 **Congratulations** on a good job. Before we can approve the project, we need to make a few changes. Find comment below:
- The ```TNW``` logo disappears on a screen resolution of ```1024x1366```. Currently, this is how it looks
sc2
```Original version```
sc3

- ```Latest new``` section does not fit well on small screen with a resolution of ```1024x1366```
sc. The width is larger than the window. Let us fix it.
- ```The App``` section also has the same bug as the latest news. Let us fix it.
sc1

Kindly make these changes and submit code review 👍 
Good luck with your next submission 😃 
_Happy coding_ 👨‍💻 
@slack on Daniel Larbi Addo

**Comment by SevlaMare** [comment]
All media queries now are clustered on end css, breakpoints for 1024px and above is working, need fix 411px (smartphones) and 768px (tablet).

**Comment by paulgureghian** [comment]
I added the cover logo, styled it, and added an h5 tag under the logo and styled it.

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello team good work on your project ❕ ❕   However there are still things to fix on this project.

## Required Changes ❗️ 

- [x] Please make your commit messages meaningful `Edited HTML` is not enough. Please be descriptive as to what changes you made in every commit. You can read about it here: https://chris.beams.io/posts/git-commit/

- [x] Your top navigation bar does not works on small screens. Also you are missing the search icon and the hamburger menu. The layout its also different on medium screens.

- [x] Your project is not completely responsive, refer to the screenshots below.

- [x] The layout is different on large screens, please use the developer tools to test your project on different screen sizes.

- [x]  I recommend you to play a game of "Find the differences" on your project and the original site, are the columns align correctly? Do the images have the overlay? Find the differences and fix them.

img1
img2
img3
img4
img5
img6

- [x] Check your CSS for repeated rules, you can read this article about it: https://speckyboy.com/good-bad-css-practices/
An example is `display: flex` that is used 7 times. 

## Optional changes

- [x] I would recommend you to follow the mobile first development methodology you can read about it here: https://medium.com/@Vincentxia77/what-is-mobile-first-design-why-its-important-how-to-make-it-7d3cf2e29d00

After making the requested changes please re-submit for review. Cheers!

## Code review by Mario Enrique Delgado Naranjo

**Review by euqueme — APPROVED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @SevlaMare and @paulgureghian  :lollipop: :balloon: 

### I can see you've made the changes requested by previous TSEs and your job so far is remarkable :clap: :medal_sports:  there are still some changes to work on :construction_worker_man: :construction_worker_man: :building_construction:  But I'm going to approve this project because I think you've done enough work to pass to the next section :heavy_check_mark: 

### Here are my suggestions :point_down: 

## Generals

**Latest Fundings**

- [x] [OPTIONAL] You are missing the Latest fundings menu I strongly recommend to add it because later on (in the bootstrap project) you'll have to make a similar behavior with the breakpoints so if you decide to do this change make sure it changes correctly in all screen breakpoints.

image

**Apps, Gear, Tech, etc**

- [x] [OPTIONAL] Please fix the tittles of your Apps, Gear, Tech, etc.. section, right now all the titles says Apps

**Latest Deals**

- [x] [OPTIONAL] Please add the "See all deals" red link in the rightmost part of the section title

## OPTIONAL

* [x] I strongly encourage the use of the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links
* [x] I also strongly encourage the use of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

### That's it, team! :raised_hands: it has been a blast to review this project :guitar: 

### Please :pray: do the changes :man_technologist: :man_technologist: (or not) and submit a project completion for because your project is approved! :tada: 

Happy Coding! :rocket: 

Any questions? reach out to me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: APPROVED :green_apple:

**Pull request merged**
